### ISSUE TITLE
Thread safe search

### ISSUE THREAD

**Issue by okhat** [xhluca/bm25s#37]
Amazing work on this! Works great.

Is retrieval thread-safe? On a glance, it seems like it should be, but I have trouble using multi-threading in a notebook. It crashes most of the time, but when it works the results are correct.

I should add that I have trouble irrespective of backend = jax or numpy.

**Comment by okhat** [comment]
I should add that I have trouble irrespective of backend = jax or numpy.

**Comment by xhluca** [comment]
That's interesting! I didn't run into issues when running 4T on kaggle. I have not tried running local notebooks, though I believe kaggle is very close to pure notebooks

Would it be possible to share a notebook where it would crash alongside steps to reproduce it?

**Comment by okhat** [comment]
I'm even more impressed by BM25s upon discovering that the crashing is coming from the evaluation library I'm using and not the search library (BM25s). It would seem that having the latter be thread-safe should be much harder than the former. Excellent work, @xhluca !

**Comment by xhluca** [comment]
Thank you for the kind words, really appreciate it! I think although the multi threaded implementation is working, I think it is possible to make it more efficient. It will definitely be an important future work.
