### ISSUE TITLE
Consider orjson as faster and more robust alternative to ujson

### ISSUE THREAD

**Issue by xhluca** [xhluca/bm25s#39]
### Discussed in https://github.com/xhluca/bm25s/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **diegovalenzuelaiturra** August  6, 2024</sup>

Hi,

Should we consider to use `orjson` as an alternative to `ujson` ?

Since `ujson` maintainers encourage their users to migrate to `orjson` because it's both faster and more robust

- https://github.com/ijl/orjson

- https://github.com/ultrajson/ultrajson

Thanks!</div>

**Comment by dantetemplar** [comment]
You can go further: https://github.com/simdjson/simdjson
