### ISSUE TITLE
ImportError: cannot import name 'Tokenizer' from 'bm25s.tokenization' (/usr/local/lib/python3.10/dist-packages/bm25s/tokenization.py)

### ISSUE THREAD

**Issue by hanxu49** [xhluca/bm25s#55]
ImportError: cannot import name 'Tokenizer' from 'bm25s.tokenization' (/usr/local/lib/python3.10/dist-packages/bm25s/tokenization.py)

**Comment by xhluca** [comment]
What version of bm25s are you using?

**Comment by hanxu49** [comment]
> What version of bm25s are you using?
> 
> Right now, `Tokenizer` class is only available in 0.2.0rc8

OK. the version is Version: 0.1.10

**Comment by xhluca** [comment]
I see. It will be included in 0.2.0, which will be release shortly. Feel free to try it in the latest prereleaae
