### ISSUE TITLE
Add BM25_pt (my library) to the acknowledgement

### ISSUE THREAD

**Issue by jxmorris12** [xhluca/bm25s#80]
Cool work, thanks for making this useful open-source tool!!

It seems that the central idea behind the scoring mechanism in this library is originally from bm25_pt: https://github.com/jxmorris12/bm25_pt

For example, the APIs are nearly identical
- https://github.com/xhluca/bm25s/blob/fa4e6348f10eadb2af9faafebbe9bc4cd1b991a0/bm25s/__init__.py#L132-L198
- https://github.com/jxmorris12/bm25_pt/blob/main/bm25_pt/bm25.py#L174-L213

would be awesome if you added an acknowledgement in the README!

**Comment by xhluca** [comment]
Yes that's right! BM25-PT was a big inspiration. I mentioned in the arxiv paper but it's important to add it to the acknolwedgement too.

**Comment by xhluca** [comment]
I added the acknolwedge here: https://github.com/xhluca/bm25s/commit/8b5ff105dc550189412da83be68de9a857b325f5

**Comment by jxmorris12** [comment]
Thank you 🙏
